# 方法一：深度优先搜索

我们对树进行深度优先搜索，在搜索过程中，我们总是先访问右子树。那么对于每一层来说，我们在这层见到的第一个结点一定是最右边的结点。

In [2]:
class TreeNode(object):
    def __init__(self, x):
        self.val = x
        self.left = None
        self.right = None

In [8]:
class Solution(object):
    def rightSideView(self, root):
        rightmost_value_at_depth = dict() # 深度为索引，存放节点的值
        max_depth = -1

        stack = [(root, 0)]
        while stack:
            node, depth = stack.pop()

            if node is not None:
                # 维护二叉树的最大深度
                max_depth = max(max_depth, depth)

                # 如果不存在对应深度的节点我们才插入
                rightmost_value_at_depth.setdefault(depth, node.val)

                stack.append((node.left, depth + 1))
                stack.append((node.right, depth + 1))

        return [rightmost_value_at_depth[depth] for depth in range(max_depth + 1)]

# 方法二：广度优先搜索

思路  
我们可以对二叉树进行层次遍历，那么对于每层来说，最右边的结点一定是最后被遍历到的。二叉树的层次遍历可以用广度优先搜索实现。

In [10]:
class Solution:
    def rightSideView(self, root):
        rightmost_value_at_depth = dict() # 深度为索引，存放节点的值
        max_depth = -1

        queue = deque([(root, 0)])
        while queue:
            node, depth = queue.popleft()

            if node is not None:
                # 维护二叉树的最大深度
                max_depth = max(max_depth, depth)

                # 由于每一层最后一个访问到的节点才是我们要的答案，因此不断更新对应深度的信息即可
                rightmost_value_at_depth[depth] = node.val

                queue.append((node.left, depth + 1))
                queue.append((node.right, depth + 1))

        return [rightmost_value_at_depth[depth] for depth in range(max_depth + 1)]

In [1]:
a = [3,30,34]

In [3]:
a = '3'
b = '30'

In [1]:
num = 33
print(bin(num))

0b100001


In [5]:
bin(33 & 1)

'0b1'

In [6]:
res = 0
res <<= 1
res

0

In [12]:
bin(33)

'0b100001'

In [24]:
from collections import deque
a = deque()

In [25]:
a.append('a')
a.append('b')

In [26]:
''.join(a)

'ab'

In [16]:
num = -33
bin(num ^ 0xffffffff)

'-0b11111111111111111111111111100000'

In [17]:
bin(~(num ^ 0xffffffff))

'0b11111111111111111111111111011111'

In [7]:
res, m = 0, 3
for i in range(32):
    res <<= 1
    print(res,bin(res))
    res |= counts[31 - i] % m

0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
2 0b10
4 0b100
8 0b1000
16 0b10000
32 0b100000


In [1]:
import numpy as np
from scipy.special import softmax

In [2]:
a = np.array([1,2,4,6,2])
softmax(a)

array([0.0057164 , 0.01553879, 0.11481697, 0.84838905, 0.01553879])

In [3]:
softmax(a/20)

array([0.18023208, 0.18947278, 0.2093998 , 0.23142257, 0.18947278])

In [4]:
softmax(a/0.05)

array([3.72007598e-44, 1.80485139e-35, 4.24835426e-18, 1.00000000e+00,
       1.80485139e-35])

In [2]:
counts = [0] * 32
for j in range(32):
    counts[j] += num & 1
    num >>= 1
    print(num,bin(num))
print(counts)

16 0b10000
8 0b1000
4 0b100
2 0b10
1 0b1
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
0 0b0
[1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [18]:
15/6

2.5

In [19]:
int(2.5)

2

In [20]:
a = 'sdadf'
a[0],a[2] = a[2],a[0]
a

TypeError: 'str' object does not support item assignment

In [21]:
def get_res2(lexicon, data):
    # 动态规划
    # dp[:i]表示前i字可以被分词成功
    n = len(data)
    dp = [False for _ in range( n +1)]
    dp[0] = True
    lexicon = set(lexicon)
    for i in range(1, n+ 1):
        if data[i - 1] in lexicon:
            dp[i] = True
        else:
            for j in range(i - 1, -1, -1):
                if dp[j]:
                    if data[j:i] in lexicon:
                        dp[i] = True

    if dp[n]:
        return "true"
    else:
        return "false"


lexicon = ["my", "name", "is", "red"]
data = "ismynamered"
res = get_res2(lexicon, data)
print(res)

true


In [5]:
a+b > b+a

True

In [22]:
''.strip()

''

In [23]:
' '.isalpha()

False

In [2]:
a.sort(key=lambda x:int(str(x)[1]) if len(str(x)) > 1 else int(str(x)[0]))
a

[30, 3, 34]

In [23]:
import pandas as pd
import re
import numpy as np

In [66]:
dic = {'name':['Pefro','Pefro','Pefro','Ramon','Ramon','Ferrero'],'items':['pear','peach','plum','grape','pear','peach']}
A = pd.DataFrame(dic)
A

name  items
0    Pefro   pear
1    Pefro  peach
2    Pefro   plum
3    Ramon  grape
4    Ramon   pear
5  Ferrero  peach

In [70]:
def cat(a,b):
    if a != b:
        c = sorted([a,b])
        return '&'.join(c)
    else:
        return a

In [53]:
B['items'] = B.apply(lambda x:cat(x['items_x'],x['items_y']),axis=1)
B

name items_x items_y       items
0     Pefro    pear    pear        pear
1     Pefro    pear   peach  pear&peach
2     Pefro    pear    plum   pear&plum
3     Pefro   peach    pear  peach&pear
4     Pefro   peach   peach       peach
5     Pefro   peach    plum  peach&plum
6     Pefro    plum    pear   plum&pear
7     Pefro    plum   peach  plum&peach
8     Pefro    plum    plum        plum
9     Ramon   grape   grape       grape
10    Ramon   grape    pear  grape&pear
11    Ramon    pear   grape  pear&grape
12    Ramon    pear    pear        pear
13  Ferrero   peach   peach       peach

In [81]:
B = pd.merge(A,A,how='inner',on='name')
B['items'] = B.apply(lambda x:cat(x['items_x'],x['items_y']),axis=1)
B.drop(['items_x','items_y'],axis=1,inplace=True)
B = B.drop_duplicates().reset_index(drop=True)
B

name       items
0    Pefro        pear
1    Pefro  peach&pear
2    Pefro   pear&plum
3    Pefro       peach
4    Pefro  peach&plum
5    Pefro        plum
6    Ramon       grape
7    Ramon  grape&pear
8    Ramon        pear
9  Ferrero       peach

# 14

In [ ]:
df['province'].fillna(value='missing',inplace=True)

# 15

In [ ]:
df[df['device']=='mobile']

# 16

In [ ]:
df['city'].value_counts()

# 17

In [ ]:
df.groupby(['group'])['pv'].sum()

# 18

In [ ]:
df.sort_values(by='pv',ascending=True)

# 19

In [ ]:
df1 = pd.read_csv(base_dir+'April.data.csv')
df = df.append(df1,ignore_index=True)

# 20

In [ ]:
df.loc[:9,:].to_csv(base_dir+'January_top10.data.csv')

In [57]:
from collections import defaultdict
dic = defaultdict(list)
for line in B.values:
    dic[line[0]].append(tuple(line[1].split('&')))

In [63]:
set(dic['Pefro'])

{('peach',),
 ('peach', 'pear'),
 ('peach', 'plum'),
 ('pear',),
 ('pear', 'peach'),
 ('pear', 'plum'),
 ('plum',),
 ('plum', 'peach'),
 ('plum', 'pear')}

In [60]:
for k,v in dic:
    dic[k] = set(dic[k])
dic

ValueError: too many values to unpack (expected 2)

In [48]:
class Solution(object):
    def combine(self, items, k):
        self.res = []
        track = []
        self.backtrack(items,k,track,0)
        return self.res

    def backtrack(self,items,k,track,start):
        #print(track)
        if len(track) <= k and len(track) > 0:
            self.res.append('&'.join(track))
            return
        if len(track) > k:
            return
        for i in range(start,len(items)):
            print(track)
            track.append(items[i])
            self.backtrack(items,k,track,i+1)
            track.pop()

In [49]:
Solution().combine(dic['Pefro'],2)

[]
[]
[]


['pear', 'peach', 'plum']

In [ ]:
res = []
for k,v in dic:
    

In [22]:
A[np.where([r'^Pe',na=False)]

name   tag
0  Pefro  mass

In [11]:
dic = {'name':['a','b','c'],'tag':['a','b','c']}
C = pd.DataFrame(dic)

In [13]:
C

name tag
0    a   a
1    b   b
2    c   c

In [12]:
A['tag'] = A['name'].apply(dict(zip(C['name'],C['tag'])))
A

AttributeError: 'a' is not a valid function for 'Series' object